### PR TITLE
Update gettoken retrieval

### PR DESCRIPTION
**Pull request by picoPWR**
- Made it easier to just copy and paste the contents of your token.
- `README` was updated also to be browser-agnostic.

### CODE REVIEW

**Comment by meepen** [comment]
Hey, I've implemented this but if you see anywhere else that needs clearing up please go ahead and update this pr.

**Comment by picoPWR** [comment]
As it stands, the readme may not work if you follow the steps exactly because the contents of the `https://steamcommunity.com/saliengame/gettoken` has unquoted keys. So either we have to add the quotes ourselves or `eval` the contents of `gettoken.json` as javascript instead of json. The latter would mean less steps for those following along in the readme.

**Comment by picoPWR** [comment]
A super minor thing really, feel free to close PR as it doesn't add much to this (awesome) project.

**Comment by meepen** [comment]
when i visit the url myself it seems to be the same and works fine?

**Pull request closed without merging**
