### PR TITLE
 BlackholeAttack + MeteorAttack by cooldown

### PR DESCRIPTION
**Pull request by TehDmitry**
subj on centerline

### CODE REVIEW

**Comment by EoD** [comment]
@TehDmitry it might be better to split up all the commits in several logically-independent pull requests.

**Comment by EoD** [comment]
@TehDmitry it might be better to get rid of all the redundant commits.

You could also rebase your code in order to avoid all these "Merge remote-tracking branch" stuff for each of your feature branches and leave only one commit.

See for example here: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by TehDmitry** [comment]
like #82 ?

**Comment by EoD** [comment]
@TehDmitry yes, that looks much nicer!

**Comment by TehDmitry** [comment]
replaced by #84

**Pull request closed without merging**
