### PR TITLE
change MAX_LEVEL

### PR DESCRIPTION
**Pull request by callmenemo491**
change MAX_LEVEL to 16
#168 shows that Level 16 is possible.

### CODE REVIEW

**Comment by SuicidalcookieS** [comment]
@callmenemo491 i'm lvl 18 :3

**Comment by SuicidalcookieS** [comment]
@callmenemo491 I set the max level to 25, that is what i believe is the max level what you can hit.

**Comment by callmenemo491** [comment]
updating the PR to have MAX_LEVEL to 25
cheers for the info @SuicidalcookieS

**Comment by callmenemo491** [comment]
PR updated.

**Comment by meepen** [comment]
i don't know if we actually NEED MAX_LEVEL anymore. any thoughts?

**Comment by callmenemo491** [comment]
thinking about it now... i think we dont need MAX_LEVEL...
i dont know much about javascript, to be able to come up with a PR to code to remove/disable the MAX_LEVEL functionality.
if you want to go ahead with the 'disable' then i'm ok with U closing this PR.

**Comment by MatthiasMoore** [comment]
I made a PR #174 that removes the leveling mode all together and prefers lower progress planets to play on higher difficulty zones.  Did a few zones testing and it seems to work properly, but I am having some latency issue with steam servers resulting in the script refreshing the page.

**Pull request closed without merging**
