### PR TITLE
Fixed bug in GetBestZone()

### PR DESCRIPTION
**Pull request by Yggdrasil128**
Fixed a bug in GetBestZone() where zones of lower difficulty didn't get discarded when isLevelling is true.

### CODE REVIEW

**Comment by Yggdrasil128** [comment]
BTW, I noticed that you are looking for the highest difficulty zone with _lowest_ progress when isLevelling is true. Why is that?
However, I adopted that into my PR.

**Comment by meepen** [comment]
can you provide an example of when this would fail compared to yours?

**Comment by thejko** [comment]
Currently on Dark Humor Planet the script is defaulting to a Medium difficulty zone instead of a harder one. With this change that issue seems to be resolved.

**Comment by Yggdrasil128** [comment]
Sure, simple example:

Let's say there are 2 zones.
Both of them are neither captured nor have a boss.
The first zone (z0) has difficulty 3, progress 0.5,
The second zone (z1) has difficulty 1, progress 0.
isLevelling is true.

After the first loop iteration, your code has z0 marked as best zone, with highestDifficulty set to 3 and maxProgress set to 0.

During the second loop iteration, the if condition in line 81 evaluates to false, so it checks line 86 and compares the progresses.
However, because z1 has less progress than z0, your code selects z1 instead of z0.

**Comment by Yggdrasil128** [comment]
Thanks for merging, I'm glad to help :)

**Pull request merged**
