### PR TITLE
format timer more friendly

### PR DESCRIPTION
**Pull request by kamsac**

### CODE REVIEW

**Comment by BoberMod** [comment]
https://github.com/meepen/salien-bot/pull/70

**Comment by meepen** [comment]
is there any more friendly way to do this? also can you make it so the time that's 0 from the left is not shown?

**Comment by kamsac** [comment]
I think it already behaves like this. Any "time" that is 0 is not shown, so for example it displays "1h 1s", instead of "0d 1h 0m 1s". If you prefer different format, just tell and I'll change it. :)

**Comment by meepen** [comment]
You're right, forgot javascript had 0 as falsey. will try it out now

**Comment by kamsac** [comment]
Also, I would write some tests for it, if there was jest set up (it's not hard to set up, but I didn't want to introduce something like this, especially in single PR).

**Comment by meepen** [comment]
11289ca

**Pull request closed without merging**
