### PR TITLE
 Planet selection

### PR DESCRIPTION
**Pull request by TehDmitry**

### CODE REVIEW

**Comment by meepen** [comment]
I don't know about this since people might want specific games in the giveaways. Any thoughts?

**Comment by TehDmitry** [comment]
If player already on the planet it will still on the  planet. Autoselect will work if planet not available

**Comment by meepen** [comment]
can you fix the conflicts real quick? this seems great

**Comment by wubstepper** [comment]
This would be great if a planet isint open

**Comment by meepen** [comment]
testing now

**Pull request merged**
