### PR TITLE
Docker support added

### PR DESCRIPTION
**Pull request by tokkenno**
Add support to build a docker image for the bot.

If you accept the pull request, then I will create an autobuild repository in Docker Hub. 

Thus, combining autobuild with [watchtower](https://github.com/v2tec/watchtower), you could run an autoupdate instance.

### CODE REVIEW

**Comment by meepen** [comment]
not really sure how docker works or how to write code for it, can anyone else confirm this works?

**Comment by tokkenno** [comment]
Docker "virtualize" the app inside a dedicated linux with the "only absolutely necessary dependencies".

You can test it easy:
1. Install docker
2. `cd` to the repository root, where the Dockerfile is located
3. Build the image: `docker build . -t meepen/salien-bot:latest` (-t set a name to the image)
4. Run the image on a container: `docker run -v ./gettoken.json:/app/gettoken.json --name salien-test meepen/salien-bot:latest` (-v allows the container to access the gettoken.json file on host. --name set a local name to the container)
5. Wait a seconds while the bot starts and generate some logs.
6. Get the console stdout with the command: `docker logs salien-test`

The usefulness of this, is that once registered the autobuild script in Docker Hub, a user will be able to run the bot with just the command `docker run -v ./gettoken.json:/app/gettoken.json meepen/salien-bot:latest` without having to install anything. If he also use a self-update utility for docker such watchtower, when a commit is pushed to the github repo, [Docker Hub](https://hub.docker.com/) will create a new image and watchtower will update it on the user server automatically and restart the container.

**Comment by meepen** [comment]
well since I have no test and you seem to know what you are talking about I will merge this as it looks fine from what I can understand.

**Comment by tokkenno** [comment]
I registered the repository on Docker Hub: https://hub.docker.com/r/reimashi/salien-bot/

This afternoon, if I have time, I will do a pull request with the instructions in the README

**Comment by Rzeszow** [comment]
@tokkenno 
I understand that you do not have automatic builds enabled?

**Comment by tokkenno** [comment]
Yes, it's an autobuild image.

Use something like [this docker-compose script](https://gist.github.com/tokkenno/cb0caffbc513790cc251a11d5732e0d1) and the container will be autoupdated.

**Comment by Rzeszow** [comment]
I mean the automatic fork code from this repository.

**Comment by denas96** [comment]
@tokkenno Maybe you should commit docker-compose.yml here?

**Comment by tokkenno** [comment]
@denas96 This afternoon (afternoon in Spain 😁) I will update the instructions in the README and yes, I can also commit the docker-compose.yml... But now, I'm a bit busy...

**Comment by denas96** [comment]
@tokkenno i've just launched your compose on aws, it works fine. I'm thinking about adding a guide about launching all this stuff on aws, because there it would work 24/7, and it's free. What @meepen is thinking about that?

**Comment by Rzeszow** [comment]
@denas96 Amazon Web Services are free ?!?

**Comment by denas96** [comment]
@Rzeszow yep. They've got free instances with 1 cpu and 1 gb ram, and this is enough

**Pull request merged**
