### PR TITLE
Countdown to level up and auto-restart in crash case

### PR DESCRIPTION
**Pull request by BoberMod**
Countdown to level up and auto-restart in crash case
image

### CODE REVIEW

**Comment by webstercharly** [comment]
I personally would have liked you to split this PR into two
1. For the Countdown to level up
2. For the auto-restart

**Comment by BoberMod** [comment]
@webstercharly, github allows this?

**Comment by webstercharly** [comment]
Does it? The GitHub PR process is all of nothing.

What I was meaning is creating two individual PRs for each of the pieces of work.

I like your time to level work but the introduction of PM2 is a deeper discussion.

**Comment by meepen** [comment]
I don't really want to have a timer to restart the script. sorry

**Pull request closed without merging**
