### PR TITLE
Add infos for userscript

### PR DESCRIPTION
**Pull request by DylanDelobel**
Tired of leaving the console open, did a quick edit to show information directly on the page itself

Saw your request on #96 here my little help

What is look like
screenshot

Will convert the Jquery for pure Javascript later to remove the dependencies

### CODE REVIEW

**Comment by DylanDelobel** [comment]
Jquery is removed, no more dependencies with the same result

**Comment by DylanDelobel** [comment]
@EoD Its show the XP for like 5 sec at the end of a map and then reset when you join another zone

This black panel could be extended with more logs, will look into later

**Comment by EoD** [comment]
@DylanDelobel Is there a way to show the XP during the duration of the fight? Like saving it somewhere and then just reading it when a fight starts.

**Comment by DylanDelobel** [comment]
ATM i just converted some console.log into the UI, will look to get more infos and a better layout

**Comment by DylanDelobel** [comment]
Thnaks :heart:

**Pull request merged**
